### ISSUE TITLE
parser ignores router with middleware

### ISSUE THREAD

**Issue by MonksterFX** [davibaltar/example-swagger-autogen#1]
First of all, greate project. I have problems in parsing when I have routers like this:

```js
// does not work
const Router = require('express').Router;
const route = new Router();
route.use(middleware);
...
```

The library not recognizes the route anymore. If I comment this out, than there is part will be showing up correctly in swagger.

```js
// works
const Router = require('express').Router;
const route = new Router();
// route.use(middleware);
...
```

**Comment by davibaltar** [comment]
Hi @MonksterFX. I tried to reproduce your problem here, but I couldn't. Can you submit a simple project that reproduces this problem and post the link here? This makes it easier to identify the problem.

**Comment by MonksterFX** [comment]
@davibaltar Thanks a lot for the fast reply. Here a minimal working example to reproduce this (My Project is huge so I made a demo)

**index.js**

```js
const express = require('express');
const router = require('./router');
const app = express();

app.get('/main', (req, res, next) => {
  return res.send('hello world');
});

app.use('/user', router);

app.listen(5656, () => {
  console.log('Server is running...');
});
```

**router.js**

```js
const express = require('express');
const router = express.Router();

function middlewareTest1(req, res, next) {
  next();
}

/* Critical Line */
router.use(middlewareTest1); // comment this line and it works

router.get('/sub', (req, res, next) => {
  res.send('Hello User');
});

module.exports = router;
```

**Comment by davibaltar** [comment]
Great @MonksterFX! Using your demo project I believe I have identified the bug. I published now a version (v2.3.3) with this fix. Test on your project, and give me feedback if it worked, please.

**Comment by MonksterFX** [comment]
Thanks a lot. Brought up another issue, but I have to test it tomorrow. I saw in your code you are doing a lot with textual analysis. Are you planing to switch to express layer model?

**Comment by davibaltar** [comment]
Ok @MonksterFX. You can bring up the issue. Today, maybe I will submit another version with more corrections. About the layer, the initial idea of the project is to be compatible with the most common frameworks, but I started with Express. In the future, the intention is to integrate other frameworks to it.
