### ISSUE TITLE
Compability with ES6

### ISSUE THREAD

**Issue by LaercioNazareno** [davibaltar/example-swagger-autogen#2]
Hi! 

I'm using your library with the node version 16.14 that uses ES6, when I execute  command npm run swagger-autogen the file swagger_output.json don't generate. Do your library has compatibility for ES6?

**Comment by marcelino-borges** [comment]
Hey!
I had to implement a whole workaround using a `.cjs` file and so on, in order to use this lib.
But I really don't like doing this. 
I guess it needs a contribution for this feature.
If I have some free time I'm gonna check this out.

**Comment by davibaltar** [comment]
Hi @marcelino-borges! I'll add this extension in the next version. Thnks!

**Comment by davibaltar** [comment]
Hi @LaercioNazareno! Sorry for the delay. What OS are you using?

**Comment by marcelino-borges** [comment]
> Hi @marcelino-borges! I'll add this extension in the next version. Thnks!

Hey, great news!! Do you have any prevision on this next version?

Thanks!!

**Comment by davibaltar** [comment]
Hi @marcelino-borges! I have just submitted the new version (2.21.9). If the problem persists, let me know.

**Comment by marcelino-borges** [comment]
Wow! You are The Flash, aren't you? haha

I noticed there's still the issue with the missing @types, but a simple workaround with a `declare module "swagger-autogen"` sorts that.

Besides that, right now I'm getting this error:
```
Error! File not found: '/src/routes/index.ts'
Swagger-autogen:  Failed
```
![190932910-95c2c8be-5b3e-4037-9b87-7a0fa654ca20](https://user-images.githubusercontent.com/33501037/191001063-9c547fbd-e850-47a4-b01d-a6aec2f60062.png)

But as you can see all my routes are into this path. Do you see anything wrong that I'm not seeing here? lol
Ps.: I'm running another config file from the command line, which calls this function of the screenshot.

I've also tried a relative path, but didn't succeed.

**Comment by davibaltar** [comment]
Hi @marcelino-borges. There was a bug in the latest versions about this. The version 2.21.10 has fixed it. Try with this version and let me know if the problem persists, please.

**Comment by marcelino-borges** [comment]
> Hi @marcelino-borges. There was a bug in the latest versions about this. The version 2.21.10 has fixed it. Try with this version and let me know if the problem persists, please.

Now I'm getting this error again, even having my file declaring the module:
![image](https://user-images.githubusercontent.com/33501037/191001590-d20533a4-5233-400d-8567-3d066efc5132.png)

**Comment by davibaltar** [comment]
About this I'll need to analise here. Could you send me a sample project that reproduces this error? That way is easier to understand and handle it.

**Comment by marcelino-borges** [comment]
There it goes: https://github.com/marcelino-borges/swagger-autogen-test
I put only the necessary files in this demo.

Thanks!

**Comment by davibaltar** [comment]
@marcelino-borges, I've implemented two files in the node_modules/swagger-autogen, and here it works with your project. But as I use MacOS, could you try in your OS, please? The two files are:

in the root of `node_modules/swagger-autogen`

**swagger-autogen.d.ts**:  
```ts
declare function swaggerAutogen (args?: any, endpointsFiles?: any, data?: any): (outputFile: any, endpointsFiles: any, data?: any) => Promise<false | {
    success: boolean;
    data: any;
}>;

export = swaggerAutogen;
```

**tsconfig.json**:  
```ts
{
  "include": [
      "src/**/*"
  ],
  "compilerOptions": {
      "module": "es2015",
      "allowJs": true,
      "declaration": true,
      "strict": true,
      "emitDeclarationOnly": true,
      "outDir": "dist",
      "declarationMap": true
  }
}
```

let me know if it works or not, please.

And if it works, I'll submit it in the next version.

**Comment by marcelino-borges** [comment]
EUREKA!

It works!!!

![image](https://user-images.githubusercontent.com/33501037/191569830-d70c3541-6d6d-4e50-9860-4f92d94ccc00.png)

Thanks!

**Comment by davibaltar** [comment]
The version 2.22.0 has implemented this. Any problem, let me know.
